logstash:
  extends:
    file: common.yml
    service: logstash
  links:
  - elastic

mongodb:
  extends:
    file: common.yml
    service: mongodb

redis:
  extends:
    file: common.yml
    service: redis

kibana:
  extends:
    file: common.yml
    service: kibana
  links:
  - elastic
elastic:
  extends:
    file: common.yml
    service: elastic

postfix:
  extends:
    file: common.yml
    service: postfix

superdesk:
  extends:
    file: common.yml
    service: superdesk
  links:
   - mongodb
   - redis
   - elastic
   - logstash
   - postfix
   - pubapi
  environment:
   - VIRTUAL_HOST=$VIRTUAL_HOST
   - VIRTUAL_PORT=$VIRTUAL_PORT
   - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
   - LETSENCRYPT_HOST=$LETSENCRYPT_HOST

pubapi:
  extends:
    file: common.yml
    service: pubapi
  links:
   - mongodb
   - redis
   - elastic
   - logstash
   - postfix
